<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<style>
    body {
        font-family: Arial, Helvetica, sans-serif;
        font-size: 12px;
        color: #000;
        margin: 20px;
    }
    .header {
        text-align: center;
        margin-bottom: 10px;
    }
    .logo {
        font-size: 42px;
        font-weight: bold;
        color: #6cba3d;
        letter-spacing: -1px;
        line-height: 1;
    }
    .logo-sub {
        font-size: 10px;
        color: #6cba3d;
        letter-spacing: 4px;
        margin-top: 2px;
    }
    .page-title {
        text-align: right;
        font-size: 11px;
        color: #333;
        margin-bottom: 5px;
    }
    h1 {
        color: #6cba3d;
        font-size: 22px;
        font-weight: bold;
        margin: 10px 0 15px 0;
        text-align: center;
    }
    .client-details {
        margin-bottom: 15px;
    }
    .client-details .heading {
        font-weight: bold;
        font-size: 13px;
        margin-bottom: 8px;
    }
    .client-details table {
        width: 100%;
        border-collapse: collapse;
    }
    .client-details td {
        padding: 4px 8px 4px 0;
        font-size: 12px;
        vertical-align: top;
    }
    .client-details .label {
        font-weight: bold;
        width: 22%;
    }
    table.assets {
        border-collapse: collapse;
        width: 100%;
        margin-top: 10px;
    }
    table.assets th, table.assets td {
        border: 1px solid #000;
        padding: 6px 8px;
        vertical-align: top;
        font-size: 11px;
    }
    table.assets th {
        background-color: #6cba3d;
        color: #fff;
        font-weight: bold;
        text-align: left;
    }
    table.assets td.no-cell {
        text-align: center;
        font-weight: bold;
    }
    table.assets td.status-cell {
        text-align: center;
        font-weight: bold;
        color: #b00;
    }
    .footer {
        margin-top: 15px;
        text-align: center;
        font-size: 10px;
        color: #555;
        border-top: 2px solid #d4ecc4;
        padding-top: 6px;
    }
</style>
</head>
<body>

<!-- PAGE TITLE -->
<div class="page-title">Asset Report/Audit Report</div>

<!-- HEADER -->
<div class="header">
    <div class="logo">ecogreen</div>
    <div class="logo-sub">IT RECYCLING</div>
</div>

<h1>Detailed Audit Report for WEEE Collection</h1>

<!-- CLIENT DETAILS -->
<div class="client-details">
    <div class="heading">Client Details</div>
    <table>
        <tr>
            <td class="label">Document Ref No:</td>
            <td>OLE954/15420</td>
            <td class="label" style="width: 20%;">Company Name:</td>
            <td>Gigantic</td>
        </tr>
        <tr>
            <td class="label">Collection Date:</td>
            <td>17.11.2025</td>
            <td class="label">Report Date:</td>
            <td>21.11.2025</td>
        </tr>
        <tr>
            <td class="label">Report Generated by:</td>
            <td colspan="3">Satinder</td>
        </tr>
    </table>
</div>

<!-- ASSETS TABLE -->
<table class="assets">
    <thead>
        <tr>
            <th style="width: 5%;">No.</th>
            <th style="width: 12%;">Type</th>
            <th style="width: 12%;">Make</th>
            <th style="width: 51%;">MODEL/SERIAL NUMBER</th>
            <th style="width: 20%;">STATUS</th>
        </tr>
    </thead>
    <tbody>
        @forelse($auditItems as $index => $item)
            @php
                $type = $item->category_name
                    ?: optional($item->category)->name
                    ?: 'N/A';

                $make = optional($item->manufacturerRel)->name
                    ?: $item->manufacturer
                    ?: $item->manufacturer_text
                    ?: '';

                $model = optional($item->productModel)->name
                    ?: $item->model
                    ?: $item->model_text
                    ?: '';

                $status =  str_replace('_', ' ', $item->process_action);
            @endphp

            <tr>
                <td class="no-cell">{{ $index + 1 }}</td>
                <td>{{ $type }}</td>
                <td>{{ $make }}</td>
                <td>
                    @if($model && $model !== 'N/A')
                        MODEL NO: {{ $model }}<br/>
                    @endif

                    @if($item->serial_number)
                        SERIAL NO: {{ $item->serial_number }}<br/>
                    @endif

                    @if($item->asset_tags)
                        Asset Tag: {{ $item->asset_tags }}<br/>
                    @else
                        Asset Tag: N/A<br/>
                    @endif

                    @if($item->storage_serial_number)
                        Storage Serial No: {{ $item->storage_serial_number }}<br/>
                    @endif

                    @if($item->second_storage_serial_number)
                        Second Storage Serial No: {{ $item->second_storage_serial_number }}<br/>
                    @endif

                    @if($item->our_asset_number)
                        Our Asset Number: {{ $item->our_asset_number }}<br/>
                    @endif

                    @if($item->item_number)
                        Item Number: {{ $item->item_number }}<br/>
                    @endif

                    @if($item->item_code)
                        Item Code: {{ $item->item_code }}<br/>
                    @endif
                </td>
                <td class="status-cell">{{ ucfirst($status) }}</td>
            </tr>
        @empty
            <tr>
                <td colspan="5" style="text-align:center;">No items found</td>
            </tr>
        @endforelse
    </tbody>
</table>

<!-- FOOTER -->
<div class="footer">
    ECOGREEN IT RECYCLING IS TRADING NAME OF COMMERCIAL IT RECYCLING LTD
</div>

</body>
</html>
